### PR TITLE
Curvilinea/bucca 3 app

### PR DESCRIPTION
**Pull request by rmoschetti**
App for story 3.
This should affect only files in \src\hub\static\apps\bucca-3-app

### CODE REVIEW

**Review by SevenIndirecto — APPROVED** [review]

**Review by SevenIndirecto — CHANGES_REQUESTED** [review]
Need to resolve conflicts

**Review by rmoschetti — COMMENTED** [review]
All changes are good

**Review by SevenIndirecto — CHANGES_REQUESTED** [review]
Hey, after merging Ew/app there are some conflicts to resolve again

**Comment by rmoschetti** [comment]
My bad, this should be good now

**Review by SevenIndirecto — APPROVED** [review]

**Pull request merged**
